export const categories = [
    {
        name: "Commercial Kitchen",
        subcategories: [
            "Ovens & Ranges",
            "Fryers",
            "Grills & Griddles",
            "Food Prep",
            "Refrigeration",
            "Dishwashing",
        ],
    },
    {
        name: "Bar Equipment",
        subcategories: [
            "Coffee Machines",
            "Blenders",
            "Ice Machines",
            "Glass Washers",
            "Bar Refrigeration",
            "Wine Coolers",
        ],
    },
    {
        name: "Tableware",
        subcategories: [
            "Crockery",
            "Cutlery",
            "Glassware",
            "Table Service",
            "Buffet Display",
        ],
    },
    {
        name: "Kitchenware",
        subcategories: [
            "Cookware",
            "Knives",
            "Utensils",
            "Pastry & Baking",
            "Storage & Transport",
        ],
    },
    {
        name: "Furniture",
        subcategories: [
            "Chairs",
            "Tables",
            "Stools",
            "Outdoor Furniture",
        ],
    },
];

export const brands = [
    {
        name: "Rational",
        description: "World leader in intelligent cooking systems for professional kitchens",
        logo: "/brands/rational.png",
        productsCount: 24,
    },
    {
        name: "Robot Coupe",
        description: "French manufacturer of commercial food processors and vegetable preparation equipment",
        logo: "/brands/robot-coupe.png",
        productsCount: 18,
    },
    {
        name: "Vitamix",
        description: "Premium commercial blenders trusted by professional chefs worldwide",
        logo: "/brands/vitamix.png",
        productsCount: 12,
    },
    {
        name: "Winterhalter",
        description: "Leading manufacturer of commercial warewashing systems",
        logo: "/brands/winterhalter.png",
        productsCount: 15,
    },
    {
        name: "Scotsman",
        description: "World's largest manufacturer of ice systems",
        logo: "/brands/scotsman.png",
        productsCount: 20,
    },
    {
        name: "Cambro",
        description: "Food storage, transport and serving solutions for foodservice",
        logo: "/brands/cambro.png",
        productsCount: 45,
    },
    {
        name: "Churchill",
        description: "British tableware manufacturer with over 200 years of heritage",
        logo: "/brands/churchill.png",
        productsCount: 67,
    },
    {
        name: "Steelite",
        description: "Premium tableware designed for the hospitality industry",
        logo: "/brands/steelite.png",
        productsCount: 89,
    },
];

export const products = [
    {
        id: "prod_01KA8CFTQ6WP59QFPBS0XF0NHJ",
        name: "Velora Luxe",
        brand: "Luxury Collection",
        price: 285000,
        originalPrice: 320000,
        discount: 11,
        image: "https://l4lqatar.blr1.digitaloceanspaces.com/velora-luxe-01KA8CFRF1QNAKM7A6SS2DGZYB.png",
        rating: 4.8,
        reviews: 45,
        inStock: true,
        category: "Furniture",
        subcategory: "Chairs",
        description: "The Velora Luxe brings a touch of luxury to bohemian design with its bold patterns and plush comfort. Its oversized shape and inviting cushions make it an ideal centerpiece for laid-back, stylish interiors.",
    },
    {
        id: "prod_01KA8CFJNP66SDM789CP70W7SD",
        name: "Velar Loft",
        brand: "Contemporary",
        price: 295000,
        originalPrice: 340000,
        discount: 13,
        image: "https://l4lqatar.blr1.digitaloceanspaces.com/velar-loft-01KA8CFGBY6YHHQC0AX2B7DHVY.png",
        rating: 4.9,
        reviews: 67,
        inStock: true,
        category: "Furniture",
        subcategory: "Chairs",
        description: "The Velar Loft offers a refined blend of modern design and opulent comfort. Upholstered in rich fabric with sleek metallic accents, this sofa delivers both luxury and a contemporary edge.",
    },
    {
        id: "prod_01KA8CFANEB9AT59A3AW8391DG",
        name: "Sutton Royale",
        brand: "Heritage",
        price: 265000,
        originalPrice: 310000,
        discount: 15,
        image: "https://l4lqatar.blr1.digitaloceanspaces.com/sutton-royale-01KA8CF8D0K1SBX1QZ3KY8FBH1.png",
        rating: 4.7,
        reviews: 54,
        inStock: true,
        category: "Furniture",
        subcategory: "Chairs",
        description: "The Sutton Royale blends eclectic design with classic bohemian comfort, featuring soft, tufted fabric and a wide, welcoming frame. Its unique style adds a touch of vintage flair.",
    },
    {
        id: "prod_01KA8CF2QCRCARQ2713XBX9KE5",
        name: "Serena Meadow",
        brand: "Classic",
        price: 245000,
        originalPrice: 280000,
        discount: 13,
        image: "https://l4lqatar.blr1.digitaloceanspaces.com/serena-meadow-01KA8CF0FFNJKFSXJJ2ETRD24F.png",
        rating: 4.6,
        reviews: 89,
        inStock: true,
        category: "Furniture",
        subcategory: "Chairs",
        description: "The Serena Meadow combines a classic silhouette with modern comfort, offering a relaxed yet polished look. Its soft upholstery and subtle curves bring timeless elegance.",
    },
    {
        id: "prod_01KA8CETRDYDF2078R8Q78T6SR",
        name: "Savannah Grove",
        brand: "Bohemian",
        price: 275000,
        originalPrice: 305000,
        discount: 10,
        image: "https://l4lqatar.blr1.digitaloceanspaces.com/savannah-grove-01KA8CERFKHGPRQSBC9988KR2E.png",
        rating: 4.8,
        reviews: 72,
        inStock: true,
        category: "Furniture",
        subcategory: "Chairs",
        description: "The Savannah Grove captures the essence of boho style with its relaxed, oversized form and eclectic fabric choices. Designed for both comfort and personality.",
    },
    {
        id: "prod_01KA8CEJSYXX3551RVMZF57129",
        name: "Paloma Haven",
        brand: "Scandinavian",
        price: 255000,
        originalPrice: 290000,
        discount: 12,
        image: "https://l4lqatar.blr1.digitaloceanspaces.com/paloma-haven-01KA8CEGHDGFMM28EGNP6DM3FE.png",
        rating: 4.9,
        reviews: 123,
        inStock: true,
        category: "Furniture",
        subcategory: "Chairs",
        description: "Minimalistic designs, neutral colors, and high-quality textures. Perfect for those who seek comfort with a clean and understated aesthetic.",
    },
    {
        id: "prod_01KA8CEB2KEV3CVSXV277ACRY9",
        name: "Oslo Serenity",
        brand: "Scandinavian",
        price: 268000,
        originalPrice: 298000,
        discount: 10,
        image: "https://l4lqatar.blr1.digitaloceanspaces.com/oslo-serenity-01KA8CE8TNRK9EQNDK4BQAHN5G.png",
        rating: 4.7,
        reviews: 98,
        inStock: true,
        category: "Furniture",
        subcategory: "Chairs",
        description: "The Oslo Serenity embodies Scandinavian minimalism with clean lines and a soft, neutral palette. Its tailored silhouette and plush cushions deliver balance.",
    },
    {
        id: "prod_01KA8CE35X2HZQZZECZR7EJBC3",
        name: "Oslo Drift",
        brand: "Scandinavian",
        price: 262000,
        originalPrice: 295000,
        discount: 11,
        image: "https://l4lqatar.blr1.digitaloceanspaces.com/oslo-drift-01KA8CE15Y5YYWKKMXNTNE83KB.png",
        rating: 4.8,
        reviews: 76,
        inStock: true,
        category: "Furniture",
        subcategory: "Chairs",
        description: "The Oslo Drift is designed for ultimate relaxation, with soft, supportive cushions and a sleek, modern frame. Ideal for contemporary, minimalist homes.",
    },
    {
        id: "prod_01KA8CDVNTV5Q7YTW8JHDPF3QK",
        name: "Nordic Haven",
        brand: "Scandinavian",
        price: 258000,
        originalPrice: 288000,
        discount: 10,
        image: "https://l4lqatar.blr1.digitaloceanspaces.com/nordic-haven-01KA8CDSE0E98KY85DJQE0MK9H.png",
        rating: 4.9,
        reviews: 134,
        inStock: true,
        category: "Furniture",
        subcategory: "Chairs",
        description: "The Nordic Haven features clean lines and soft textures, embodying the essence of Scandinavian design. Natural tones bring effortless serenity.",
    },
    {
        id: "prod_01KA8CDKSW84BMMJZFFXJQKV5D",
        name: "Nordic Breeze",
        brand: "Scandinavian",
        price: 252000,
        originalPrice: 282000,
        discount: 11,
        image: "https://l4lqatar.blr1.digitaloceanspaces.com/nordic-breeze-01KA8CDHHR0YG8PFM9J9RH0XCK.png",
        rating: 4.7,
        reviews: 87,
        inStock: true,
        category: "Furniture",
        subcategory: "Chairs",
        description: "The Nordic Breeze is a refined expression of Scandinavian minimalism, with its crisp silhouette and airy aesthetic. Perfect for serene living spaces.",
    },
    {
        id: "prod_01KA8CDBHS6WR51GP2ZC5CKFKD",
        name: "Monaco Flair",
        brand: "Contemporary",
        price: 298000,
        originalPrice: 335000,
        discount: 11,
        image: "https://l4lqatar.blr1.digitaloceanspaces.com/monaco-flair-01KA8CD99MJEVKP4RC6FH4DJ43.png",
        rating: 4.8,
        reviews: 65,
        inStock: true,
        category: "Furniture",
        subcategory: "Chairs",
        description: "The Monaco Flair combines sleek metallic accents with rich fabric, delivering a bold, luxurious statement for modern living rooms.",
    },
    {
        id: "prod_01KA8CD3JJ7VN2G70QB91CPM9W",
        name: "Havenhill Estate",
        brand: "Heritage",
        price: 285000,
        originalPrice: 320000,
        discount: 11,
        image: "https://l4lqatar.blr1.digitaloceanspaces.com/havenhill-estate-01KA8CD1AE2E1F36H9SPK5YRDS.png",
        rating: 4.9,
        reviews: 112,
        inStock: true,
        category: "Furniture",
        subcategory: "Chairs",
        description: "The Havenhill Estate brings traditional charm with elegant curves and classic silhouette. A timeless piece combining comfort and style.",
    },
    {
        id: "prod_01KA8CCVHN1VESCGEB6MGCQ8BP",
        name: "Everly Estate",
        brand: "Luxury Collection",
        price: 305000,
        originalPrice: 345000,
        discount: 12,
        image: "https://l4lqatar.blr1.digitaloceanspaces.com/everly-estate-01KA8CCSH8BZRPQXTRV6YSMJ15.png",
        rating: 4.9,
        reviews: 145,
        inStock: true,
        category: "Furniture",
        subcategory: "Chairs",
        description: "The Everly Estate offers a blend of modern elegance and plush luxury, with sleek lines and soft velvet upholstery. Perfect for upscale interiors.",
    },
    {
        id: "prod_01KA8CCKSYK7KA0N2C3VV6BKEH",
        name: "Cypress Retreat",
        brand: "Classic",
        price: 248000,
        originalPrice: 280000,
        discount: 11,
        image: "https://l4lqatar.blr1.digitaloceanspaces.com/cypress-retreat-01KA8CCHJ3TYVBNGSMJ2M5HZ00.png",
        rating: 4.7,
        reviews: 93,
        inStock: true,
        category: "Furniture",
        subcategory: "Chairs",
        description: "The Cypress Retreat is a nod to traditional design with elegant lines and durable, high-quality upholstery. A timeless choice for any home.",
    },
    {
        id: "prod_01KA8CCBRAPBVCQP6VXMDMR4BJ",
        name: "Belime Estate",
        brand: "Heritage",
        price: 278000,
        originalPrice: 315000,
        discount: 12,
        image: "https://l4lqatar.blr1.digitaloceanspaces.com/belime-estate-01KA8CC9QN4ZZSZCMJ3QYRB637.png",
        rating: 4.8,
        reviews: 108,
        inStock: true,
        category: "Furniture",
        subcategory: "Chairs",
        description: "The Belime Estate exudes classic sophistication with its tufted back and rich fabric. Perfect for traditional, elegant interiors.",
    },
    {
        id: "prod_01KA8CC43FW0PAPPZ6AVSTEYZZ",
        name: "Astrid Curve",
        brand: "Bohemian",
        price: 268000,
        originalPrice: 298000,
        discount: 10,
        image: "https://l4lqatar.blr1.digitaloceanspaces.com/astrid-curve-01KA8CC23JVP13ZNQAN4X7RGZT.png",
        rating: 4.7,
        reviews: 82,
        inStock: true,
        category: "Furniture",
        subcategory: "Chairs",
        description: "The Astrid Curve combines flowing curves and cozy, textured fabric for a truly bohemian vibe. Perfect for eclectic living spaces.",
    },
];

// Collections
export const collections = [
    {
        id: "collection_01",
        name: "Complete Kitchen Starter",
        description: "Everything you need to set up a professional kitchen from scratch",
        image: "/collections/kitchen-starter.jpg",
        productCount: 24,
        price: 1250000,
    },
    {
        id: "collection_02",
        name: "Bar Essentials Pro",
        description: "Professional bar setup with coffee machines, blenders, and refrigeration",
        image: "/collections/bar-essentials.jpg",
        productCount: 12,
        price: 850000,
    },
    {
        id: "collection_03",
        name: "Restaurant Dining Complete",
        description: "Full tableware and serving solution for fine dining establishments",
        image: "/collections/dining-complete.jpg",
        productCount: 156,
        price: 450000,
    },
    {
        id: "collection_04",
        name: "Pastry Chef Bundle",
        description: "Specialized equipment for pastry and baking operations",
        image: "/collections/pastry-bundle.jpg",
        productCount: 18,
        price: 380000,
    },
];

// Special Offers
export const offers = [
    {
        id: "offer_01",
        title: "Flash Sale: Commercial Ovens",
        description: "Up to 25% off on selected commercial ovens",
        discount: 25,
        validUntil: "2025-12-31",
        image: "/offers/oven-sale.jpg",
    },
    {
        id: "offer_02",
        title: "Bar Equipment Bonanza",
        description: "Buy 2 Get 1 Free on bar refrigeration units",
        discount: 33,
        validUntil: "2025-11-30",
        image: "/offers/bar-sale.jpg",
    },
    {
        id: "offer_03",
        title: "Tableware Clearance",
        description: "Massive discounts on Churchill and Steelite ranges",
        discount: 40,
        validUntil: "2025-11-25",
        image: "/offers/tableware-clearance.jpg",
    },
];

// Gift Voucher Options
export const giftVouchers = [
    { value: 10000, label: "Rs. 10,000" },
    { value: 25000, label: "Rs. 25,000" },
    { value: 50000, label: "Rs. 50,000" },
    { value: 100000, label: "Rs. 100,000" },
    { value: 250000, label: "Rs. 250,000" },
];

// Commercial Projects Portfolio
export const projects = [
    {
        id: "project_01",
        name: "Cinnamon Grand Hotel Kitchen Renovation",
        client: "Cinnamon Grand Colombo",
        category: "Hotel",
        description: "Complete kitchen renovation including cooking, refrigeration, and dishwashing systems",
        image: "/projects/cinnamon-grand.jpg",
        completedDate: "2024-08-15",
        value: 15000000,
    },
    {
        id: "project_02",
        name: "Ministry of Crab Restaurant Setup",
        client: "Ministry of Crab",
        category: "Restaurant",
        description: "High-end kitchen setup for award-winning seafood restaurant",
        image: "/projects/ministry-of-crab.jpg",
        completedDate: "2024-06-20",
        value: 8500000,
    },
    {
        id: "project_03",
        name: "Starbucks Colombo City Centre",
        client: "Starbucks Coffee",
        category: "Cafe",
        description: "Complete coffee shop equipment installation",
        image: "/projects/starbucks.jpg",
        completedDate: "2024-09-10",
        value: 4200000,
    },
];
